apiVersion: v1
kind: Pod
metadata:
  name: pod-voting-app
  labels:
    name: pod-voting-app
    app: demo-voting-app
spec:
  containers:
  - name: voting-app
    image: dockersamples/examplevotingapp_vote