apiVersion: v1
kind: Pod
metadata:
  name: pod-worker-app
  labels:
    name: pod-worker-app
    app: demo-voting-app
spec:
  containers:
  - name: worker-app
    image: dockersamples/examplevotingapp_worker